/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : BitsCS.c
**     Project     : fw_prototype
**     Processor   : MC9S08DZ60CLC
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 03.28, CPU db: 3.00.025
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2016-05-05, 17:12, # CodeGen: 13
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**         Port name                   : PTB
**
**         Bit mask of the port        : $0003
**         Number of bits/pins         : 2
**         Single bit numbers          : 0 to 1
**         Values range                : 0 to 3
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 3 = 003H
**         Initial pull option         : off
**
**         Port data register          : PTBD      [$0002]
**         Port control register       : PTBDD     [$0003]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    22   |   PTB0_PIB0_ADP8
**                    1      |    24   |   PTB1_PIB1_ADP9
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents    :
**         GetDir - bool BitsCS_GetDir(void);
**         GetVal - byte BitsCS_GetVal(void);
**         PutVal - void BitsCS_PutVal(byte Val);
**         GetBit - bool BitsCS_GetBit(byte Bit);
**         PutBit - void BitsCS_PutBit(byte Bit, bool Val);
**         SetBit - void BitsCS_SetBit(byte Bit);
**         ClrBit - void BitsCS_ClrBit(byte Bit);
**         NegBit - void BitsCS_NegBit(byte Bit);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file BitsCS.c
** @version 03.28
** @brief
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
*/         
/*!
**  @addtogroup BitsCS_module BitsCS module documentation
**  @{
*/         

/* MODULE BitsCS. */

#include "BitsCS.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  BitsCS_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const  byte BitsCS_Table[2U] = { /* Table of mask constants */
   0x01U, 0x02U
};

static byte BitsCS_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<2U) ? BitsCS_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  BitsCS_GetVal (component BitsIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 3)
** ===================================================================
*/
byte BitsCS_GetVal(void)
{
  return (byte)(getReg8(PTBD) & 0x03U); /* Return port data */
}

/*
** ===================================================================
**     Method      :  BitsCS_PutVal (component BitsIO)
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void BitsCS_PutVal(byte Val)
{
  Val &= 0x03U;                        /* Mask output value */
  setReg8(PTBD, (getReg8(PTBD) & (byte)(~(byte)0x03U)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  BitsCS_GetBit (component BitsIO)
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 1)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool BitsCS_GetBit(byte Bit)
{
  byte const Mask = BitsCS_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PTBD) & Mask) == Mask)? 1U: 0U); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  BitsCS_PutBit (component BitsIO)
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 1)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void BitsCS_PutBit(byte Bit, bool Val)
{
  byte const Mask = BitsCS_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTBD, Mask);           /* [bit (Bit)]=0x01U */
  } else { /* !Val */
    clrReg8Bits(PTBD, Mask);           /* [bit (Bit)]=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  BitsCS_ClrBit (component BitsIO)
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
void BitsCS_ClrBit(byte Bit)
{
  byte const Mask = BitsCS_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PTBD, Mask);             /* [bit (Bit)]=0x00U */
}

/*
** ===================================================================
**     Method      :  BitsCS_SetBit (component BitsIO)
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
void BitsCS_SetBit(byte Bit)
{
  byte const Mask = BitsCS_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PTBD, Mask);             /* [bit (Bit)]=0x01U */
}

/*
** ===================================================================
**     Method      :  BitsCS_NegBit (component BitsIO)
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void BitsCS_NegBit(byte Bit)
{
  byte const Mask = BitsCS_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PTBD, Mask);          /* [bit (Bit)]=invert */
}

/*
** ===================================================================
**     Method      :  BitsCS_GetDir (component BitsIO)
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always <true>, Output only)
**                      <false> = Input, <true> = Output
** ===================================================================
*/
/*
bool BitsCS_GetDir(void)

**  This method is implemented as a macro. See BitsCS.h file.  **
*/


/* END BitsCS. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
