/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : TIKrnl.h
**     Project     : fw_prototype
**     Processor   : MC9S08DZ60CLC
**     Component   : TimerInt
**     Version     : Component 02.161, Driver 01.23, CPU db: 3.00.025
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2016-05-05, 09:38, # CodeGen: 2
**     Abstract    :
**         This component "TimerInt" implements a periodic interrupt.
**         When the component and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings    :
**         Timer name                  : TPM2 (16-bit)
**         Compare name                : TPM20
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-16
**             Clock                   : 500000 Hz
**           Initial period/frequency
**             Xtal ticks              : 100000
**             microseconds            : 12500
**             milliseconds            : 12
**             seconds (real)          : 0.0125
**             Hz                      : 80
**
**         Runtime setting             : period/frequency interval (continual setting)
**             ticks                   : 8000 to 800000 ticks
**             microseconds            : 1000 to 100000 microseconds
**             milliseconds            : 1 to 100 milliseconds
**             seconds (real)          : 0.001 to 0.1 seconds
**             Hz                      : 10 to 1000 Hz
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TPM2CNT   [$0061]
**              Mode                   : TPM2SC    [$0060]
**              Run                    : TPM2SC    [$0060]
**              Prescaler              : TPM2SC    [$0060]
**
**         Compare registers
**              Compare                : TPM2C0V   [$0066]
**
**         Flip-flop registers
**              Mode                   : TPM2C0SC  [$0065]
**     Contents    :
**         SetPeriodTicks16 - byte TIKrnl_SetPeriodTicks16(word Ticks);
**         SetPeriodTicks32 - byte TIKrnl_SetPeriodTicks32(dword Ticks);
**         SetPeriodUS      - byte TIKrnl_SetPeriodUS(word Time);
**         SetPeriodMS      - byte TIKrnl_SetPeriodMS(word Time);
**         SetFreqHz        - byte TIKrnl_SetFreqHz(word Freq);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file TIKrnl.h
** @version 01.23
** @brief
**         This component "TimerInt" implements a periodic interrupt.
**         When the component and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
*/         
/*!
**  @addtogroup TIKrnl_module TIKrnl module documentation
**  @{
*/         

#ifndef __TIKrnl
#define __TIKrnl

/* MODULE TIKrnl. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Cpu.h"

/* PUBLISHED CONSTANTS */
#define TIKrnl_SPT16_MIN   0x1F40U     /* Lower bound of interval for method SetPeriodTicks16 */
#define TIKrnl_SPT16Min    TIKrnl_SPT16_MIN /* Deprecated */
#define TIKrnl_SPT16_MAX   0xFFFFU     /* Upper bound of interval for method SetPeriodTicks16 */
#define TIKrnl_SPT16Max    TIKrnl_SPT16_MAX /* Deprecated */
#define TIKrnl_SPT32_MIN   0x1F40UL    /* Lower bound of interval for method SetPeriodTicks32 */
#define TIKrnl_SPT32Min    TIKrnl_SPT32_MIN /* Deprecated */
#define TIKrnl_SPT32_MAX   0x000C3500UL /* Upper bound of interval for method SetPeriodTicks32 */
#define TIKrnl_SPT32Max    TIKrnl_SPT32_MAX /* Deprecated */
#define TIKrnl_SPUS_MIN    0x03E8U     /* Lower bound of interval for method SetPeriodUS */
#define TIKrnl_SPUSMin     TIKrnl_SPUS_MIN /* Deprecated */
#define TIKrnl_SPUS_MAX    0xFFFFU     /* Upper bound of interval for method SetPeriodUS */
#define TIKrnl_SPUSMax     TIKrnl_SPUS_MAX /* Deprecated */
#define TIKrnl_SPMS_MIN    0x01U       /* Lower bound of interval for method SetPeriodMS */
#define TIKrnl_SPMSMin     TIKrnl_SPMS_MIN /* Deprecated */
#define TIKrnl_SPMS_MAX    0x64U       /* Upper bound of interval for method SetPeriodMS */
#define TIKrnl_SPMSMax     TIKrnl_SPMS_MAX /* Deprecated */
#define TIKrnl_SFREQ_HZ_MIN 0x0AU      /* Lower bound of interval for method SetFreqHz */
#define TIKrnl_SFHzMin     TIKrnl_SFREQ_HZ_MIN /* Deprecated */
#define TIKrnl_SFREQ_HZ_MAX 0x03E8U    /* Upper bound of interval for method SetFreqHz */
#define TIKrnl_SFHzMax     TIKrnl_SFREQ_HZ_MAX /* Deprecated */

byte TIKrnl_SetPeriodTicks16(word Ticks);
/*
** ===================================================================
**     Method      :  TIKrnl_SetPeriodTicks16 (component TimerInt)
**     Description :
**         This method sets the new period of the generated events.
**         The period is expressed in main oscillator (usualy External
**         osc., internal osc. if exits and external osc. is disabled)
**         ticks as a 16-bit unsigned integer number.
**         This method is available only if the runtime setting type
**         'from interval' is selected in the Timing dialog box in
**         the Runtime setting area.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ticks           - Period to set [in Xtal ticks]
**                      (8000 to 65535 ticks)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte TIKrnl_SetPeriodTicks32(dword Ticks);
/*
** ===================================================================
**     Method      :  TIKrnl_SetPeriodTicks32 (component TimerInt)
**     Description :
**         This method sets the new period of the generated events.
**         The period is expressed in main oscillator (usualy External
**         osc., internal osc. if exits and external osc. is disabled)
**         ticks as a 32-bit unsigned integer number.
**         This method is available only if the runtime setting type
**         'from interval' is selected in the Timing dialog box in
**         the Runtime setting area.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ticks           - Period to set [in Xtal ticks]
**                      (8000 to 800000 ticks)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte TIKrnl_SetPeriodUS(word Time);
/*
** ===================================================================
**     Method      :  TIKrnl_SetPeriodUS (component TimerInt)
**     Description :
**         This method sets the new period of the generated events.
**         The period is expressed in microseconds as a 16-bit
**         unsigned integer number.
**         This method is available only if the runtime setting type
**         'from interval' is selected in the Timing dialog box in
**         the Runtime setting area.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Time            - Period to set [in microseconds]
**                      (1000 to 65535 microseconds)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte TIKrnl_SetPeriodMS(word Time);
/*
** ===================================================================
**     Method      :  TIKrnl_SetPeriodMS (component TimerInt)
**     Description :
**         This method sets the new period of the generated events.
**         The period is expressed in miliseconds as a 16-bit
**         unsigned integer number.
**         This method is available only if the runtime setting type
**         'from interval' is selected in the Timing dialog box in
**         the Runtime setting area.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Time            - Period to set [in miliseconds]
**                      (1 to 100 milliseconds)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte TIKrnl_SetFreqHz(word Freq);
/*
** ===================================================================
**     Method      :  TIKrnl_SetFreqHz (component TimerInt)
**     Description :
**         This method sets the new frequency of the generated
**         events. The frequency is expressed in Hz as a 16-bit
**         unsigned integer number.
**         This method is available only if the runtime setting type
**         'from interval' is selected in the Timing dialog box in
**         the Runtime setting area.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Freq            - Frequency to set [in Hz]
**                      (10 to 1000 Hz)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

__interrupt void TIKrnl_Interrupt(void);
/*
** ===================================================================
**     Method      :  TIKrnl_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the component event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void TIKrnl_Init(void);
/*
** ===================================================================
**     Method      :  TIKrnl_Init (component TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END TIKrnl. */

#endif /* ifndef __TIKrnl */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
